version: '3.8'

services:
  frontend:
    hostname: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - backend
    networks:
      - app-network
    environment:
      - VITE_API_URL=http://backend:8080

  backend:
    hostname: backend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - .env
    entrypoint: /bin/bash
    command:
      - -c
      - |
        uwsgi --http 0.0.0.0:8080 --master -p 2 -w src.wsgi:app
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 128M
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
